DROP TABLE IF EXISTS LineItem;
DROP TABLE IF EXISTS TimeSheet;

CREATE TABLE LineItem (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timesheet_id INTEGER,
    lineItemDate  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lineItemMinutes  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT NOT NULL
);

CREATE TABLE TimeSheet (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    submittedDate  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT,
    hourlyRate INTEGER
);
