DROP TABLE IF EXISTS LineItem;

CREATE TABLE LineItem (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lineItemDate  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lineItemMinutes  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT NOT NULL
);

CREATE TABLE Rate (
    hourlyRate INTEGER
);
